USE [master]
GO

/****** Object:  Database [LoginWPF]    Script Date: 3/3/2017 4:10:17 PM ******/
CREATE DATABASE [LoginWPF]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LoginWPF', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\LoginWPF.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LoginWPF_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\LoginWPF_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LoginWPF] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LoginWPF].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LoginWPF] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LoginWPF] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LoginWPF] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LoginWPF] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LoginWPF] SET ARITHABORT OFF 
GO

ALTER DATABASE [LoginWPF] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LoginWPF] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LoginWPF] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LoginWPF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LoginWPF] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LoginWPF] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LoginWPF] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LoginWPF] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LoginWPF] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LoginWPF] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LoginWPF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LoginWPF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LoginWPF] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LoginWPF] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LoginWPF] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LoginWPF] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LoginWPF] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LoginWPF] SET RECOVERY FULL 
GO

ALTER DATABASE [LoginWPF] SET  MULTI_USER 
GO

ALTER DATABASE [LoginWPF] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LoginWPF] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LoginWPF] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LoginWPF] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LoginWPF] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LoginWPF] SET  READ_WRITE 
GO

